# Generated by Django 4.1.4 on 2023-04-15 09:42

from django.db import migrations, models
import django.db.models.deletion
import django_pgschemas.schema
import django_pgschemas.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditUnion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(max_length=63, unique=True, validators=[django_pgschemas.utils.check_schema_name])),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(default='321 092 2093', max_length=20)),
                ('email', models.EmailField(default='support@support.com', max_length=50)),
                ('logo', models.ImageField(null=True, upload_to='images')),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(django_pgschemas.schema.SchemaDescriptor, models.Model),
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('folder', models.SlugField(blank=True, max_length=253)),
                ('is_primary', models.BooleanField(default=True)),
                ('redirect_to_primary', models.BooleanField(default=False)),
                ('domain', models.CharField(max_length=100)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='creditunions.creditunion')),
            ],
            options={
                'abstract': False,
                'unique_together': {('domain', 'folder')},
            },
        ),
    ]
