# Generated by Django 4.1.4 on 2023-05-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditunions', '0003_creditunion_form_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditunion',
            name='header_color',
            field=models.CharField(default='rgb(114, 143, 206)', max_length=20),
        ),
    ]
