# Generated by Django 4.1.4 on 2023-05-23 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditunions', '0004_creditunion_header_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditunion',
            name='buttons_color',
            field=models.CharField(default='black', max_length=20),
        ),
    ]
