# Generated by Django 4.1.4 on 2023-05-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditunions', '0005_creditunion_buttons_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditunion',
            name='buttons_color',
            field=models.CharField(default='#027FAA', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditunion',
            name='footer_color',
            field=models.CharField(default='rgb(245, 222, 179)', max_length=20),
        ),
        migrations.AlterField(
            model_name='creditunion',
            name='header_color',
            field=models.CharField(default='#F9F4F4', max_length=20),
        ),
    ]
