# Generated by Django 4.1.4 on 2023-12-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('creditunions', '0006_alter_creditunion_buttons_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditunion',
            name='allow_international_wires',
            field=models.BooleanField(default=True),
        ),
    ]
