# Generated by Django 4.1.4 on 2023-05-26 20:50

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import recurrence.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('job_title', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('signup_confirmation', models.BooleanField(default=False)),
                ('is_approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='WireFormDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20, null=True)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('Foreign Currency', 'Foreign Currency')], max_length=40, null=True)),
                ('recurrent', models.BooleanField(default=False)),
                ('recurrency', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('sending_account_number', models.CharField(max_length=60)),
                ('sending_account_type', models.CharField(max_length=60)),
                ('sending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_date', models.DateField()),
                ('recipient_name', models.CharField(max_length=60)),
                ('recipient_account_type', models.CharField(max_length=60)),
                ('recipient_account_number', models.CharField(max_length=60)),
                ('recipient_routing_number', models.CharField(max_length=60)),
                ('receiving_bank_name', models.CharField(max_length=60)),
                ('receiving_street_address', models.CharField(max_length=60)),
                ('receiving_bank_city', models.CharField(max_length=60, null=True)),
                ('receiving_bank_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('OT', 'OTHER')], max_length=20)),
                ('receiving_bank_zipcode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Invalid ZIP CODE')])),
                ('intermediary_bank_name', models.CharField(max_length=60, null=True)),
                ('intermediary_bank_st_adress', models.CharField(max_length=60, null=True)),
                ('intermediary_bank_country', models.CharField(choices=[('USA', 'USA'), ('OTHER', 'OTHER')], max_length=20, null=True)),
                ('intermediary_bank_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('OT', 'OTHER')], max_length=20, null=True)),
                ('intermediary_bank_country_name', models.CharField(max_length=20, null=True)),
                ('intermediary_bank_post_code', models.CharField(max_length=20, null=True)),
                ('intermediary_bank_swift', models.CharField(max_length=20, null=True)),
                ('intermediary_bank_iban', models.CharField(max_length=40, null=True)),
                ('purpose_of_wire', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('slug', models.SlugField(default='', editable=False, max_length=30)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formpage.client')),
            ],
        ),
        migrations.CreateModel(
            name='ReccurentOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formpage.client')),
                ('wire_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formpage.wireformdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formpage.client')),
                ('wire_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formpage.wireformdetails')),
            ],
        ),
        migrations.CreateModel(
            name='FormTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('destination', models.CharField(choices=[('domestic', 'Domestic'), ('international', 'International')], max_length=20)),
                ('currency', models.CharField(choices=[('USD', 'US Dollar'), ('Foreign Currency', 'Foreign Currency')], max_length=40)),
                ('sending_account_number', models.CharField(max_length=60)),
                ('sending_account_type', models.CharField(max_length=60)),
                ('sending_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('effective_date', models.DateField()),
                ('recurrent', models.BooleanField(default=False)),
                ('recurrency', recurrence.fields.RecurrenceField(blank=True, null=True)),
                ('recipient_name', models.CharField(max_length=60)),
                ('recipient_account_type', models.CharField(max_length=60)),
                ('recipient_account_number', models.CharField(max_length=60)),
                ('recipient_routing_number', models.CharField(max_length=60)),
                ('receiving_bank_name', models.CharField(max_length=60)),
                ('receiving_street_address', models.CharField(max_length=60)),
                ('receiving_bank_city', models.CharField(max_length=60, null=True)),
                ('receiving_bank_state', models.CharField(max_length=60)),
                ('receiving_bank_zipcode', models.CharField(max_length=5, validators=[django.core.validators.RegexValidator('^[0-9]{5}$', 'Invalid ZIP CODE')])),
                ('intermediary_bank_name', models.CharField(max_length=60, null=True)),
                ('intermediary_bank_st_adress', models.CharField(max_length=60, null=True)),
                ('intermediary_bank_country', models.CharField(choices=[('USA', 'USA'), ('OTHER', 'OTHER')], max_length=20, null=True)),
                ('intermediary_bank_country_name', models.CharField(max_length=20, null=True)),
                ('intermediary_bank_state', models.CharField(choices=[('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming'), ('OT', 'OTHER')], max_length=20, null=True)),
                ('intermediary_bank_post_code', models.CharField(max_length=20, null=True)),
                ('intermediary_bank_swift', models.CharField(max_length=20, null=True)),
                ('intermediary_bank_iban', models.CharField(max_length=40, null=True)),
                ('purpose_of_wire', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formpage.client')),
            ],
        ),
    ]
