# Generated by Django 4.1.4 on 2023-09-05 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formpage', '0007_formtemplate_intermediary_routing_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formtemplate',
            name='receiving_bank_zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='wireformdetails',
            name='receiving_bank_zipcode',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
