# Generated by Django 4.1.4 on 2023-09-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formpage', '0008_alter_formtemplate_receiving_bank_zipcode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formtemplate',
            name='sending_account_number',
        ),
        migrations.RemoveField(
            model_name='wireformdetails',
            name='sending_account_number',
        ),
        migrations.CreateModel(
            name='UserAccountNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.CharField(max_length=60)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='formpage.client')),
            ],
        ),
    ]
