# Generated by Django 4.1.4 on 2023-09-22 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formpage', '0009_remove_formtemplate_sending_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='formtemplate',
            name='sending_account_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='formpage.useraccountnumber'),
        ),
        migrations.AddField(
            model_name='wireformdetails',
            name='sending_account_number',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='formpage.useraccountnumber'),
        ),
    ]
