# Generated by Django 4.1.4 on 2024-04-02 06:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        (
            "formpage",
            "0014_rename_destination_wireformdetails_destincreate_useration_and_more",
        ),
    ]

    operations = [
        migrations.DeleteModel(
            name="CustomUser",
        ),
    ]
