"""
Django settings for wireform project.

Generated by 'django-admin startproject' using Django 4.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/4.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.1/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-ukp60gg-^^o%c($#0#w2fkyg7^6m6a-psgs$r1^8045#9o$_(j'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
CSRF_TRUSTED_ORIGINS = ['https://*.truwires.com']
ALLOWED_HOSTS = ["137.184.108.21","www.truwires.com","truwires.com",".truwires.com","localhost", "127.0.0.1", "*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_tables2',
    'formpage',
    'recurrence',
    'widget_tweaks',
    'celery',
    'drf_yasg',
    'django_celery_results',
    'django_celery_beat',
    'creditunions',
    'rest_framework',
    'rest_framework_swagger',
]

MIDDLEWARE = [
    "django_pgschemas.middleware.TenantMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
   
]

ROOT_URLCONF = 'wireform.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR / "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'formpage.context_processors.tenant_context',
            ],
        },
    },
]
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-mail.outlook.com'
EMAIL_HOST_USER = 'noreply@trutreasury.com'
EMAIL_HOST_PASSWORD ='Jaq73184'
EMAIL_PORT          = 587
EMAIL_USE_TLS       = True
WSGI_APPLICATION = 'wireform.wsgi.application'
NEW_CREDITUNION_ADMIN = 'admin1'

# Database
# https://docs.djangoproject.com/en/4.1/ref/settings/#databases


DATABASES = {
    "default": {
        'ENGINE': 'django_pgschemas.postgresql_backend',
        "NAME": "wireformdb",
        "USER": "postgres",
        "PASSWORD": "Testword1!",
    }
}

DATABASE_ROUTERS = (
    "django_pgschemas.routers.SyncRouter",
)

TENANTS = {
    "public": {
        "APPS": [
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.contenttypes',
            'django.contrib.sessions',
            'django.contrib.messages',
            'django.contrib.staticfiles',
            "widget_tweaks",
            'recurrence',
            'celery',
            'django_celery_results',
            'django_celery_beat',

            "django_pgschemas",
            "formpage",
            "creditunions",
        ],
    },
    "main": {
        "APPS": [
            "formpage",

        ],
        "DOMAINS": [],
        "FALLBACK_DOMAINS": ["localhost"],
        "URLCONF": "wireform.urls",
    },
    "default": {
        "TENANT_MODEL": "creditunions.CreditUnion",
        "DOMAIN_MODEL": "creditunions.Domain",
        "APPS": [
            'django.contrib.admin',
            'django.contrib.auth',
            'django.contrib.sessions',
            "formpage",
        ],
        "URLCONF": "wireform.urls",
    }
}


INSTALLED_APPS = []
for schema in TENANTS:
    INSTALLED_APPS += [app for app in TENANTS[schema]["APPS"] if app not in INSTALLED_APPS]

ROOT_URLCONF = TENANTS["default"]["URLCONF"]

PUBLIC_SCHEMA_NAME = 'public'

# Password validation
# https://docs.djangoproject.com/en/4.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.1/howto/static-files/


STATIC_URL = 'static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# STATIC_ROOT=os.path.join(BASE_DIR,'static')
#STATIC_ROOT = os.path.join(BASE_DIR, 'static')

MEDIA_ROOT=os.path.join(BASE_DIR,'media')

MEDIA_URL='/media/'

# STATIC_URL = '/static/'
# STATICFILES_DIRS = [
#     os.path.join(BASE_DIR, 'static'),
# ]
# STATIC_ROOT = os.path.join(BASE_DIR,'assets')

# MEDIA_URL='/media/'
# MEDIA_ROOT=os.path.join(BASE_DIR,'media/')



# Default primary key field type
# https://docs.djangoproject.com/en/4.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
WIRE_TITLE_MAX_LENGTH = 30


# CELERY v 5

CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
CELERY_ACCEPT_CONTENT = ['application/json']
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TASK_SERIALIZER = 'json'
CELERY_TIMEZONE = 'US/Eastern'

CELERY_RESULT_BACKEND = 'django-db'

#CELERY BEAT
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

#Celery

# CELERY_BROKER_URL = 'redis://127.0.0.1:6379'
# accept_content = ['application/json']
# result_serializer = 'json'
# task_serializer = 'json'
# timezone = 'Africa/Nairobi'

# result_backend = 'django-db'

# #CELERY BEAT
# CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'
